let Keyboard = (function() {
    let pressedKeys = {};
    
    let keyPress = function(e) {       
        pressedKeys[e.keyCode] = e.timeStamp;
        
        let code = numericToCodeMap[e.keyCode];
        if (code == 'DOM_VK_UP' || code == 'DOM_VK_DOWN' || code == 'DOM_VK_LEFT' || code == 'DOM_VK_RIGHT' || code == 'DOM_VK_SPACE' || code == 'DOM_VK_END' || code == 'DOM_VK_HOME' || code == 'DOM_VK_PAGE_UP' || code == 'DOM_VK_PAGE_DOWN') {
            e.preventDefault();
            return false;
        }
    }
    
    let keyRelease = function(e) {
        delete pressedKeys[e.keyCode];
    }
    
    document.addEventListener('keydown', keyPress);
    document.addEventListener('keyup', keyRelease);
    
    let codeToNumericMap = {
		DOM_VK_CANCEL: 3,                                                                            
		DOM_VK_HELP: 6,
		DOM_VK_BACK_SPACE: 8,
		DOM_VK_TAB: 9,
		DOM_VK_CLEAR: 12,
		DOM_VK_RETURN: 13,
		DOM_VK_ENTER: 14,
		DOM_VK_SHIFT: 16,
		DOM_VK_CONTROL: 17,
		DOM_VK_ALT: 18,
		DOM_VK_PAUSE: 19,
		DOM_VK_CAPS_LOCK: 20,
		DOM_VK_ESCAPE: 27,
		DOM_VK_SPACE: 32,
		DOM_VK_PAGE_UP: 33,
		DOM_VK_PAGE_DOWN: 34,
		DOM_VK_END: 35,
		DOM_VK_HOME: 36,
		DOM_VK_LEFT: 37,
		DOM_VK_UP: 38,
		DOM_VK_RIGHT: 39,
		DOM_VK_DOWN: 40,
		DOM_VK_PRINTSCREEN: 44,
		DOM_VK_INSERT: 45,
		DOM_VK_DELETE: 46,
		DOM_VK_0: 48,
		DOM_VK_1: 49,
		DOM_VK_2: 50,
		DOM_VK_3: 51,
		DOM_VK_4: 52,
		DOM_VK_5: 53,
		DOM_VK_6: 54,
		DOM_VK_7: 55,
		DOM_VK_8: 56,
		DOM_VK_9: 57,
		DOM_VK_SEMICOLON: 59,
		DOM_VK_EQUALS: 61,
		DOM_VK_A: 65,
		DOM_VK_B: 66,
		DOM_VK_C: 67,
		DOM_VK_D: 68,
		DOM_VK_E: 69,
		DOM_VK_F: 70,
		DOM_VK_G: 71,
		DOM_VK_H: 72,
		DOM_VK_I: 73,
		DOM_VK_J: 74,
		DOM_VK_K: 75,
		DOM_VK_L: 76,
		DOM_VK_M: 77,
		DOM_VK_N: 78,
		DOM_VK_O: 79,
		DOM_VK_P: 80,
		DOM_VK_Q: 81,
		DOM_VK_R: 82,
		DOM_VK_S: 83,
		DOM_VK_T: 84,
		DOM_VK_U: 85,
		DOM_VK_V: 86,
		DOM_VK_W: 87,
		DOM_VK_X: 88,
		DOM_VK_Y: 89,
		DOM_VK_Z: 90,
		DOM_VK_CONTEXT_MENU: 93,
		DOM_VK_NUMPAD0: 96,
		DOM_VK_NUMPAD1: 97,
		DOM_VK_NUMPAD2: 98,
		DOM_VK_NUMPAD3: 99,
		DOM_VK_NUMPAD4: 100,
		DOM_VK_NUMPAD5: 101,
		DOM_VK_NUMPAD6: 102,
		DOM_VK_NUMPAD7: 103,
		DOM_VK_NUMPAD8: 104,
		DOM_VK_NUMPAD9: 105,
		DOM_VK_MULTIPLY: 106,
		DOM_VK_ADD: 107,
		DOM_VK_SEPARATOR: 108,
		DOM_VK_SUBTRACT: 109,
		DOM_VK_DECIMAL: 110,
		DOM_VK_DIVIDE: 111,
		DOM_VK_F1: 112,
		DOM_VK_F2: 113,
		DOM_VK_F3: 114,
		DOM_VK_F4: 115,
		DOM_VK_F5: 116,
		DOM_VK_F6: 117,
		DOM_VK_F7: 118,
		DOM_VK_F8: 119,
		DOM_VK_F9: 120,
		DOM_VK_F10: 121,
		DOM_VK_F11: 122,
		DOM_VK_F12: 123,
		DOM_VK_F13: 124,
		DOM_VK_F14: 125,
		DOM_VK_F15: 126,
		DOM_VK_F16: 127,
		DOM_VK_F17: 128,
		DOM_VK_F18: 129,
		DOM_VK_F19: 130,
		DOM_VK_F20: 131,
		DOM_VK_F21: 132,
		DOM_VK_F22: 133,
		DOM_VK_F23: 134,
		DOM_VK_F24: 135,
		DOM_VK_NUM_LOCK: 144,
		DOM_VK_SCROLL_LOCK: 145,
		DOM_VK_COMMA: 188,
		DOM_VK_PERIOD: 190,
		DOM_VK_SLASH: 191,
		DOM_VK_BACK_QUOTE: 192,
		DOM_VK_OPEN_BRACKET: 219,
		DOM_VK_BACK_SLASH: 220,
		DOM_VK_CLOSE_BRACKET: 221,
		DOM_VK_QUOTE: 222,
		DOM_VK_META: 224
	};
    
    let numericToCodeMap = {
    };
    
    for (let kvp in codeToNumericMap) {
        numericToCodeMap[codeToNumericMap[kvp]] = kvp;
    }
    
    let codeToStringMap = {
		DOM_VK_CANCEL: 'Cancel',                                                                            
		DOM_VK_HELP: 'Help',
		DOM_VK_BACK_SPACE: 'Bckspc',
		DOM_VK_TAB: 'Tab',
		DOM_VK_CLEAR: 'Clear',
		DOM_VK_RETURN: 'Return',
		DOM_VK_ENTER: 'Enter',
		DOM_VK_SHIFT: 'Shift',
		DOM_VK_CONTROL: 'Ctrl',
		DOM_VK_ALT: 'Alt',
		DOM_VK_PAUSE: 'Pause',
		DOM_VK_CAPS_LOCK: 'Caps',
		DOM_VK_ESCAPE: 'Esc',
		DOM_VK_SPACE: 'Spc',
		DOM_VK_PAGE_UP: 'PgUp',
		DOM_VK_PAGE_DOWN: 'PgDn',
		DOM_VK_END: 'End',
		DOM_VK_HOME: 'Home',
		DOM_VK_LEFT: 'Left',
		DOM_VK_UP: 'Up',
		DOM_VK_RIGHT: 'Right',
		DOM_VK_DOWN: 'Down',
		DOM_VK_PRINTSCREEN: 'PrtSc',
		DOM_VK_INSERT: 'Insert',
		DOM_VK_DELETE: 'Delete',
		DOM_VK_0: '0',
		DOM_VK_1: '1',
		DOM_VK_2: '2',
		DOM_VK_3: '3',
		DOM_VK_4: '4',
		DOM_VK_5: '5',
		DOM_VK_6: '6',
		DOM_VK_7: '7',
		DOM_VK_8: '8',
		DOM_VK_9: '9',
		DOM_VK_SEMICOLON: ';',
		DOM_VK_EQUALS: '=',
		DOM_VK_A: 'A',
		DOM_VK_B: 'B',
		DOM_VK_C: 'C',
		DOM_VK_D: 'D',
		DOM_VK_E: 'E',
		DOM_VK_F: 'F',
		DOM_VK_G: 'G',
		DOM_VK_H: 'H',
		DOM_VK_I: 'I',
		DOM_VK_J: 'J',
		DOM_VK_K: 'K',
		DOM_VK_L: 'L',
		DOM_VK_M: 'M',
		DOM_VK_N: 'N',
		DOM_VK_O: 'O',
		DOM_VK_P: 'P',
		DOM_VK_Q: 'Q',
		DOM_VK_R: 'R',
		DOM_VK_S: 'S',
		DOM_VK_T: 'T',
		DOM_VK_U: 'U',
		DOM_VK_V: 'V',
		DOM_VK_W: 'W',
		DOM_VK_X: 'X',
		DOM_VK_Y: 'Y',
		DOM_VK_Z: 'Z',
		DOM_VK_CONTEXT_MENU: 'Ctxt',
		DOM_VK_NUMPAD0: 'Pad0',
		DOM_VK_NUMPAD1: 'Pad1',
		DOM_VK_NUMPAD2: 'Pad2',
		DOM_VK_NUMPAD3: 'Pad3',
		DOM_VK_NUMPAD4: 'Pad4',
		DOM_VK_NUMPAD5: 'Pad5',
		DOM_VK_NUMPAD6: 'Pad6',
		DOM_VK_NUMPAD7: 'Pad7',
		DOM_VK_NUMPAD8: 'Pad8',
		DOM_VK_NUMPAD9: 'Pad9',
		DOM_VK_MULTIPLY: '*',
		DOM_VK_ADD: '+',
		DOM_VK_SEPARATOR: 'Sep',
		DOM_VK_SUBTRACT: '-',
		DOM_VK_DECIMAL: 'Dec',
		DOM_VK_DIVIDE: 'Div',
		DOM_VK_F1: 'F1',
		DOM_VK_F2: 'F2',
		DOM_VK_F3: 'F3',
		DOM_VK_F4: 'F4',
		DOM_VK_F5: 'F5',
		DOM_VK_F6: 'F6',
		DOM_VK_F7: 'F7',
		DOM_VK_F8: 'F8',
		DOM_VK_F9: 'F9',
		DOM_VK_F10: 'F10',
		DOM_VK_F11: 'F11',
		DOM_VK_F12: 'F12',
		DOM_VK_F13: 'F13',
		DOM_VK_F14: 'F14',
		DOM_VK_F15: 'F15',
		DOM_VK_F16: 'F16',
		DOM_VK_F17: 'F17',
		DOM_VK_F18: 'F18',
		DOM_VK_F19: 'F19',
		DOM_VK_F20: 'F20',
		DOM_VK_F21: 'F21',
		DOM_VK_F22: 'F22',
		DOM_VK_F23: 'F23',
		DOM_VK_F24: 'F24',
		DOM_VK_NUM_LOCK: 'NumLock',
		DOM_VK_SCROLL_LOCK: 'ScrlLock',
		DOM_VK_COMMA: ',',
		DOM_VK_PERIOD: '.',
		DOM_VK_SLASH: '/',
		DOM_VK_BACK_QUOTE: '\`',
		DOM_VK_OPEN_BRACKET: '[',
		DOM_VK_BACK_SLASH: '\\',
		DOM_VK_CLOSE_BRACKET: ']',
		DOM_VK_QUOTE: '\'',
		DOM_VK_META: 'Meta'
	};
    
    return {
        pressedKeys: pressedKeys,
        numericToCodeMap : numericToCodeMap,
        codeToNumericMap : codeToNumericMap,
        codeToStringMap : codeToStringMap,
    }
}());